language: php
php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm

before_script:
  - nohup bash -c "java -Djava.library.path=./DynamoDBLocal_lib -jar dynamodb_local/DynamoDBLocal.jar --port 3000" && sleep 2
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction

script: phpunit
